export default {
  IDENTIFIER: 'IDENTIFIER',
  START_REF: 'START_REF',
  END_REF: 'END_REF',
  MODIFIER: 'MODIFIER',
  ESCAPE: '\\',
  TEXT: 'TEXT',
  SAVE_DIVIDER: 'SAVE_DIVIDER',
  UNKNOWN: 'UNKNOWN',
  START: 'START',
  END: 'END'
}